name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: "23.2.0"
      - name: Install
        run: npm i
      - name: Create App .env
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_VITE_API: ${{ secrets.VITE_API }}
          directory: apps/app/
      - name: Create Backend .env
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_DATABASE: ${{ secrets.DATABASE }}
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_APP_URL: ${{ secrets.APP_URL }}
          directory: apps/backend/
      - name: Build
        run: npm run build
      - name: Lint check
        run: npm run lint
      - name: TS check
        run: npm run ts
      - name: Deploy App
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: apps/app/dist
          target: ${{ secrets.SSH_PATH }}
      - name: Deploy Backend
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "apps/backend/build,apps/backend/package.json,apps/backend/package-lock.json,apps/backend/.env"
          target: ${{ secrets.SSH_PATH }}
      - name: Install Backend deps and Reload PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.SSH_PATH_BACKEND }}
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm i
            pm2 reload fit
